/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Compression;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * @return the xx
     */
    public int getXx() {
        return xx;
    }

    /**
     * @param xx the xx to set
     */
    public void setXx(int xx) {
        this.xx = xx;
    }

    /**
     * @return the xy
     */
    public int getXy() {
        return xy;
    }

    /**
     * @param xy the xy to set
     */
    public void setXy(int xy) {
        this.xy = xy;
    }

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        pnlOverlay.setBackground(new Color(0, 0, 0, 150));
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon/icons8_Archive_Folder_64px.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        second = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        pnlOverlay = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtusername = new subjtextfiledsk15.SubJTextField();
        txtpassword = new javax.swing.JPasswordField();
        lbExit = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlLoader = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));

        second.setBackground(new java.awt.Color(255, 255, 255));
        second.setLayout(new java.awt.CardLayout());

        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlOverlay.setBackground(new java.awt.Color(0, 0, 0));
        pnlOverlay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlOverlayMouseDragged(evt);
            }
        });
        pnlOverlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlOverlayMousePressed(evt);
            }
        });
        pnlOverlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        pnlOverlay.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Compression Software");
        pnlOverlay.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("User Name");
        pnlOverlay.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        pnlOverlay.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 290, 30));

        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordKeyTyped(evt);
            }
        });
        pnlOverlay.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 290, 30));

        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit (2).png"))); // NOI18N
        lbExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
        });
        pnlOverlay.add(lbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 20, 20));

        lbLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Login_30px_1.png"))); // NOI18N
        lbLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLoginMouseClicked(evt);
            }
        });
        pnlOverlay.add(lbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 50, 40));

        pnlLogin.add(pnlOverlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bb.jpg"))); // NOI18N
        pnlLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 380));

        second.add(pnlLogin, "card3");

        pnlLoader.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageGIF/ring.gif"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 195, 148));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Loading...");

        javax.swing.GroupLayout pnlLoaderLayout = new javax.swing.GroupLayout(pnlLoader);
        pnlLoader.setLayout(pnlLoaderLayout);
        pnlLoaderLayout.setHorizontalGroup(
            pnlLoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaderLayout.createSequentialGroup()
                .addGroup(pnlLoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoaderLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel3))
                    .addGroup(pnlLoaderLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnlLoaderLayout.setVerticalGroup(
            pnlLoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaderLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        second.add(pnlLoader, "card3");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(second, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(second, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(480, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int xx,xy;
    private void pnlOverlayMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOverlayMouseDragged
        try{
            int x=evt.getXOnScreen();
            int y=evt.getYOnScreen();
            this.setLocation(x-xx, y-xy);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlOverlayMouseDragged

    private void pnlOverlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOverlayMousePressed
        try{
            xx=evt.getX();
            xy=evt.getY();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlOverlayMousePressed

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        try{
            System.exit(0);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lbExitMouseClicked

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        try{
            if(evt.getKeyChar()==10){
                txtpassword.grabFocus();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameKeyTyped

    private void txtpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyTyped
        try{
            if(evt.getKeyChar()==10){
                lbLogin.grabFocus();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordKeyTyped

    private void lbLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLoginMouseClicked
        // TODO add your handling code here:
        try{
            String user=txtusername.getText();
            String pass=String.valueOf(txtpassword.getPassword());
            
            pnlLoader.setVisible(true);
            pnlLogin.setVisible(false);
            if(user.equals("admin") && pass.equalsIgnoreCase("123") || user.equals("root") && pass.equalsIgnoreCase("123")){
                new java.util.Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    Compresssion.main(null);
                    dispose();
                }
                },1000*3);
            }else if(user==("admin") && user==("root")){
                new java.util.Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    Compresssion.main(null);
                    dispose();
                }
                },1000*3);
            }else{
                new java.util.Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    LogIn msl=new LogIn();
                    msl.setVisible(true);
                    dispose();
                    }
                },1000*3);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_lbLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JPanel pnlLoader;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlOverlay;
    private javax.swing.JPanel second;
    private javax.swing.JPasswordField txtpassword;
    private subjtextfiledsk15.SubJTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
